import { useMemo } from 'react'

export default function AdminAnalytics({ orders = [] }) {
  const stats = useMemo(() => {
    const revenue = orders.reduce((sum, order) => sum + Number(order.total_dh ?? order.total ?? 0), 0)
    const regions = orders.reduce((map, order) => { const city = order.city || 'Other'; map[city] = (map[city] || 0) + 1; return map }, {})
    return { revenue, average: orders.length ? revenue / orders.length : 0, regions }
  }, [orders])
  return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3">{[['Revenue trajectory', `${stats.revenue.toLocaleString()} DH`], ['Average order value', `${Math.round(stats.average).toLocaleString()} DH`], ['Orders velocity', `${orders.length} total orders`]].map(([label, value]) => <article key={label} className="border border-amber-500/30 bg-neutral-950 p-5 shadow-[0_0_24px_rgba(197,160,89,0.08)]"><p className="text-[10px] uppercase tracking-widest text-amber-400">{label}</p><p className="mt-4 font-mono text-2xl text-white">{value}</p></article>)}</div><div className="grid gap-6 lg:grid-cols-2"><section className="border border-neutral-800 bg-neutral-950 p-6"><h2 className="font-serif text-2xl">Revenue trajectory</h2><div className="mt-8 flex h-40 items-end gap-2">{orders.slice(0, 12).reverse().map((order, index) => <div key={order.id || index} className="flex-1 bg-amber-400/80 shadow-[0_0_14px_rgba(197,160,89,0.5)]" style={{ height: `${Math.max(12, Math.min(100, Number(order.total_dh ?? order.total ?? 0) / Math.max(stats.average, 1) * 45))}%` }} />)}</div></section><section className="border border-neutral-800 bg-neutral-950 p-6"><h2 className="font-serif text-2xl">Moroccan regional distribution</h2><div className="mt-6 space-y-4">{Object.entries(stats.regions).map(([city, count]) => <div key={city}><div className="flex justify-between text-xs"><span>{city}</span><span className="text-amber-400">{count}</span></div><div className="mt-2 h-1 bg-neutral-800"><div className="h-1 bg-amber-400" style={{ width: `${count / Math.max(orders.length, 1) * 100}%` }} /></div></div>)}</div></section></div><section className="border border-neutral-800 bg-neutral-950 p-6"><h2 className="font-serif text-2xl">Live activity feed</h2><ul className="mt-5 space-y-3 text-xs text-neutral-400">{orders.slice(0, 6).map((order) => <li key={order.id} className="border-l border-amber-400 pl-3"><span className="text-amber-300">{order.id}</span> · {order.status || 'order received'} · {order.city || 'Morocco'}</li>)}</ul></section></div>
}
