import { RotateCcw, X } from 'lucide-react'

const defaultGroups = [
  ['Categories', 'category', ['High Jewelry', 'Fine Jewelry', 'Timepieces', 'Haute Horlogerie']],
  ['Metals & Materials', 'metal', ['18k Yellow Gold', '18k Rose Gold', '18k White Gold', 'Platinum']],
  ['Gemstones', 'gemstone', ['Diamonds', 'Emeralds', 'Sapphires', 'Rubies']],
]

export default function FilterSidebar({ filters, onChange, onReset, mobile = false, categoryOptions }) {
  const groups = [[defaultGroups[0][0], defaultGroups[0][1], categoryOptions?.length ? categoryOptions : defaultGroups[0][2]], ...defaultGroups.slice(1)]
  const active = Object.entries(filters).flatMap(([key, values]) => Array.isArray(values) ? values.map((value) => ({ key, value })) : [])
  const toggle = (key, value) => onChange(key, filters[key].includes(value) ? filters[key].filter((item) => item !== value) : [...filters[key], value])

  return <aside className={mobile ? 'space-y-6' : 'hidden w-64 flex-shrink-0 space-y-6 lg:block'}><div className="flex items-center justify-between"><h2 className="text-xs uppercase tracking-[0.2em]">Filter</h2>{active.length > 0 && <button type="button" onClick={onReset} className="inline-flex items-center gap-1 text-[10px] uppercase tracking-widest text-amber-400"><RotateCcw size={12} /> Reset All</button>}</div>{groups.map(([label, key, options]) => <fieldset key={key} className="border-t border-neutral-800 pt-4"><legend className="text-[10px] uppercase tracking-[0.18em] text-neutral-400">{label}</legend><div className="mt-3 space-y-2">{options.map((option) => <label key={option} className="flex items-center gap-3 text-xs text-neutral-400"><input type="checkbox" checked={filters[key].includes(option)} onChange={() => toggle(key, option)} className="accent-amber-500" />{option}</label>)}</div></fieldset>)}<fieldset className="border-t border-neutral-800 pt-4"><legend className="text-[10px] uppercase tracking-[0.18em] text-neutral-400">Price Range (DH)</legend><div className="mt-3 grid grid-cols-2 gap-2"><input type="number" min="0" step="5000" value={filters.minPrice} onChange={(event) => onChange('minPrice', event.target.value)} aria-label="Minimum price" className="w-full border border-neutral-800 bg-neutral-900 px-2 py-2 text-xs outline-none focus:border-amber-500" /><input type="number" min="0" step="5000" value={filters.maxPrice} onChange={(event) => onChange('maxPrice', event.target.value)} aria-label="Maximum price" placeholder="500,000+" className="w-full border border-neutral-800 bg-neutral-900 px-2 py-2 text-xs outline-none focus:border-amber-500" /></div></fieldset><label className="flex items-center justify-between border-t border-neutral-800 pt-4 text-xs text-neutral-300">Boutique Exclusive / Onsite Only<input type="checkbox" checked={filters.exclusive} onChange={(event) => onChange('exclusive', event.target.checked)} className="h-4 w-4 accent-amber-500" /></label>{active.length > 0 && <div className="flex flex-wrap gap-2 border-t border-neutral-800 pt-4">{active.map(({ key, value }) => <button type="button" key={`${key}-${value}`} onClick={() => toggle(key, value)} className="inline-flex items-center gap-1 border border-amber-500/40 px-2 py-1 text-[10px] uppercase tracking-wider text-amber-300">{value}<X size={11} /></button>)}</div>}</aside>
}
