import { X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useCart } from '../context/CartContext'
import { useWishlist } from '../context/WishlistContext'

export default function WishlistDrawer() {
  const { addToCart } = useCart()
  const { wishlistItems, removeFromWishlist, isWishlistOpen, setIsWishlistOpen } = useWishlist()
  return <div className={`fixed inset-0 z-[75] transition-opacity ${isWishlistOpen ? 'pointer-events-auto opacity-100' : 'pointer-events-none opacity-0'}`}><button type="button" aria-label="Close wishlist" onClick={() => setIsWishlistOpen(false)} className="absolute inset-0 bg-black/70" /><aside className={`absolute inset-y-0 right-0 w-full max-w-md bg-neutral-950 p-6 text-white transition-transform ${isWishlistOpen ? 'translate-x-0' : 'translate-x-full'}`}><header className="flex justify-between border-b border-neutral-800 pb-5"><h2 className="font-serif text-2xl uppercase tracking-widest">Wishlist</h2><button type="button" aria-label="Close wishlist" onClick={() => setIsWishlistOpen(false)}><X /></button></header><div className="mt-6 space-y-5">{wishlistItems.length ? wishlistItems.map((item) => { const image = item.main_image_url || item.image || item.images?.[0]; const price = Number(item.price ?? item.price_dh ?? 0); return <article key={item.id} className="flex gap-4 border-b border-neutral-800 pb-5"><Link to={`/product/${item.id}`} onClick={() => setIsWishlistOpen(false)} className="shrink-0"><img src={image} alt={item.name} className="h-24 w-20 object-cover transition-opacity hover:opacity-80" /></Link><div className="flex-1"><Link to={`/product/${item.id}`} onClick={() => setIsWishlistOpen(false)} className="font-serif hover:text-amber-300">{item.name}</Link><p className="mt-2 text-sm text-amber-400">{price.toLocaleString()} DH</p><div className="mt-4 flex gap-3"><button type="button" onClick={() => addToCart({ ...item, price })} className="text-[10px] uppercase tracking-widest text-amber-300 hover:text-amber-200">Add to Bag</button><button type="button" onClick={() => removeFromWishlist(item.id)} className="text-[10px] uppercase tracking-widest text-neutral-500 hover:text-white">Remove</button></div></div></article> }) : <p className="py-16 text-center text-sm text-neutral-500">Your wishlist is empty.</p>}</div></aside></div>
}
